# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 19:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170123_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='place',
            name='placename',
            field=models.CharField(blank=True, max_length=50, verbose_name='place name'),
        ),
    ]
